---
# A list of pipelines where each item is a YAML representation of https://api.go.cd/current/#the-pipeline-config-object
pipelines:
  - group: Debug_Pipeline_Group
    pipeline:
        label_template: ${COUNT}
        enable_pipeline_locking: false
        name: hello-world-build
        template: null
        materials:
          - type: git
            attributes:
              url: https://github.com/gocd-contrib/getting-started-repo.git
              filter: null
              invert_filter: false
              name: null
              auto_update: true
              branch: master
              submodule_folder: null
        stages:
          - name: defaultStage
            fetch_materials: true
            clean_working_directory: false
            never_cleanup_artifacts: false
            environment_variables: 
              -
            jobs:
              - name: defaultJob
                run_instance_count: null
                timeout: 0
                environment_variables:
                  -
                resources:
                  -
                tasks:
                  - type: exec
                    attributes:
                      run_if:
                        - passed
                      command: ./build
                      working_directory: null
        
        
